services:
  uranabot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - uranabot-network
    healthcheck:
      test: ["CMD", "node", "dist/healthcheck.js"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

networks:
  uranabot-network:
    driver: bridge

volumes:
  uranabot-data:
