name: Deploy Uranabot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run type check
      run: npm run type-check

    - name: Build project
      run: npm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          # Создать директорию проекта если не существует
          sudo mkdir -p /opt/uranabot
          sudo chown $(whoami):$(whoami) /opt/uranabot
          cd /opt/uranabot
          
          # Остановить существующий контейнер
          docker compose down || true
          
          # Загрузить новый образ
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # Создать docker-compose.yml автоматически
          cat > docker-compose.yml << 'EOF'
          version: '3.8'
          
          services:
            uranabot:
              image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
              environment:
                - NODE_ENV=production
                - BOT_TOKEN=${{ secrets.BOT_TOKEN }}
                - LOG_LEVEL=info
                - PORT=3000
              ports:
                - "3000:3000"
              restart: unless-stopped
              networks:
                - uranabot-network
              healthcheck:
                test: ["CMD", "node", "dist/healthcheck.js"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
          
          networks:
            uranabot-network:
              driver: bridge
          
          volumes:
            uranabot-data:
          EOF
          
          # Создать .env файл
          cat > .env << 'EOF'
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          NODE_ENV=production
          LOG_LEVEL=info
          PORT=3000
          EOF
          
          # Запустить новый контейнер
          docker compose up -d
          
          # Показать статус
          docker compose ps
          docker compose logs --tail=50
          
          # Очистка старых образов
          docker image prune -f

  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Wait for deployment and health check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          cd /opt/uranabot
          
          # Ждем запуска контейнера
          echo "Waiting for container to start..."
          sleep 30
          
          # Проверяем статус контейнеров
          echo "=== Container Status ==="
          docker compose ps
          
          # Проверяем логи
          echo "=== Recent Logs ==="
          docker compose logs --tail=30
          
          # Проверяем health check
          echo "=== Health Check ==="
          docker compose exec -T uranabot node dist/healthcheck.js || echo "Health check failed"
          
          # Проверяем что бот отвечает
          echo "=== Bot Status ==="
          if docker compose logs | grep -q "Uranabot is running"; then
            echo "✅ Bot is running successfully!"
          else
            echo "❌ Bot may not be running properly"
            exit 1
          fi
